name: Bar

on:
  workflow_dispatch:

jobs:
  check_latest:
    name: Check If Release Is Needed
    runs-on: ubuntu-20.04
    steps:
      - name: Step is going to fail
        continue-on-error: true
        run: exit 1
      - name: Step to run on failure
        if: ${{ failure() }}
        run: |
          echo "The previous step totally failed!"
