name: Foo

on:
  workflow_dispatch:

jobs:
  check_latest:
    name: Check If Release Is Needed
    runs-on: ubuntu-20.04
    steps:
      - name: Get last released version
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: philrz
          repo: build-sha-test
      - name: Download last build_sha
        id: latest_sha
        run: |
          curl -L https://github.com/philrz/build-sha-test/releases/download/${{ steps.latest_release.outputs.release }}/build_sha.txt > build_sha.txt
          echo "sha=$(cat build_sha.txt)" >> $GITHUB_OUTPUT
      - name: Show what is up
        run: |
          echo "latest sha is: ${{ steps.latest_sha.outputs.sha }}"
          echo "github.sha is ${{ github.sha }}"
      - name: Compare last build_sha to current sha
        if: ${{ steps.latest_sha.outputs.sha == github.sha }}
        run: |
          echo "SHA has not changed so no build will be generated"
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}

    outputs:
      version: ${{ steps.latest_release.outputs.release }}
